### ISSUE TITLE
Is there a way to use esbuild with component testing?

### ISSUE THREAD

**Issue by TomaszG** [bahmutov/cypress-esbuild-preprocessor#243]
Is there a way to use esbuild preprocessor instead of webpack with component testing? I tried to configure it in the same way as for e2e testing, but still, webpack was used. Changing the bundler to `esbuild` in `cypress.config.json` files results in an error message about an unsupported bundler.

```js
	component: {
		devServer: {
			framework: 'next',
			bundler: 'webpack',
		},
	},
```

**Comment by lmiller1990** [comment]
`file:preprocesor` is only for End to End - Component Testing uses a dev-server architecture.

You could write your own dev server with esbuild https://docs.cypress.io/guides/component-testing/component-framework-configuration#Custom-Dev-Server or just use the Cypress Vite Dev Server (works out of the box, just choose "React" + "Vite" when you set up component testing). You might run into some weirdness, since Vite doens't integrate with Next.js, though...

But since you are using Next, this probably doesn't make sense - you likely want to be bundling your components with the same bundler as production (which is webpack?)

**Comment by TomaszG** [comment]
FYI, since NextJS 13, the Turbopack bundler is used instead of Webpack: https://nextjs.org/docs/architecture/turbopack
